/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SandboxImport } from './routes/sandbox'
import { Route as NavbarImport } from './routes/_navbar'
import { Route as NavbarIndexImport } from './routes/_navbar/index'
import { Route as NavbarAuthedImport } from './routes/_navbar/_authed'
import { Route as AuthSignupImport } from './routes/_auth/signup'
import { Route as AuthPasswordResetImport } from './routes/_auth/password-reset'
import { Route as AuthPasswordForgotImport } from './routes/_auth/password-forgot'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as NavbarAuthedRecipeNewImport } from './routes/_navbar/_authed/recipe/new'
import { Route as NavbarAuthedRecipeSidebarImport } from './routes/_navbar/_authed/recipe/_sidebar'
import { Route as NavbarAuthedRecipeSidebarIndexImport } from './routes/_navbar/_authed/recipe/_sidebar/index'
import { Route as NavbarAuthedRecipeSidebarRecipeIdImport } from './routes/_navbar/_authed/recipe/_sidebar/$recipeId'

// Create Virtual Routes

const NavbarAuthedRecipeImport = createFileRoute('/_navbar/_authed/recipe')()

// Create/Update Routes

const SandboxRoute = SandboxImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRoute,
} as any)

const NavbarRoute = NavbarImport.update({
  id: '/_navbar',
  getParentRoute: () => rootRoute,
} as any)

const NavbarIndexRoute = NavbarIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NavbarRoute,
} as any)

const NavbarAuthedRoute = NavbarAuthedImport.update({
  id: '/_authed',
  getParentRoute: () => NavbarRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthPasswordResetRoute = AuthPasswordResetImport.update({
  id: '/_auth/password-reset',
  path: '/password-reset',
  getParentRoute: () => rootRoute,
} as any)

const AuthPasswordForgotRoute = AuthPasswordForgotImport.update({
  id: '/_auth/password-forgot',
  path: '/password-forgot',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const NavbarAuthedRecipeRoute = NavbarAuthedRecipeImport.update({
  id: '/recipe',
  path: '/recipe',
  getParentRoute: () => NavbarAuthedRoute,
} as any)

const NavbarAuthedRecipeNewRoute = NavbarAuthedRecipeNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => NavbarAuthedRecipeRoute,
} as any)

const NavbarAuthedRecipeSidebarRoute = NavbarAuthedRecipeSidebarImport.update({
  id: '/_sidebar',
  getParentRoute: () => NavbarAuthedRecipeRoute,
} as any)

const NavbarAuthedRecipeSidebarIndexRoute =
  NavbarAuthedRecipeSidebarIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NavbarAuthedRecipeSidebarRoute,
  } as any)

const NavbarAuthedRecipeSidebarRecipeIdRoute =
  NavbarAuthedRecipeSidebarRecipeIdImport.update({
    id: '/$recipeId',
    path: '/$recipeId',
    getParentRoute: () => NavbarAuthedRecipeSidebarRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_navbar': {
      id: '/_navbar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NavbarImport
      parentRoute: typeof rootRoute
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/password-forgot': {
      id: '/_auth/password-forgot'
      path: '/password-forgot'
      fullPath: '/password-forgot'
      preLoaderRoute: typeof AuthPasswordForgotImport
      parentRoute: typeof rootRoute
    }
    '/_auth/password-reset': {
      id: '/_auth/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof AuthPasswordResetImport
      parentRoute: typeof rootRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/_navbar/_authed': {
      id: '/_navbar/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NavbarAuthedImport
      parentRoute: typeof NavbarImport
    }
    '/_navbar/': {
      id: '/_navbar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof NavbarIndexImport
      parentRoute: typeof NavbarImport
    }
    '/_navbar/_authed/recipe': {
      id: '/_navbar/_authed/recipe'
      path: '/recipe'
      fullPath: '/recipe'
      preLoaderRoute: typeof NavbarAuthedRecipeImport
      parentRoute: typeof NavbarAuthedImport
    }
    '/_navbar/_authed/recipe/_sidebar': {
      id: '/_navbar/_authed/recipe/_sidebar'
      path: '/recipe'
      fullPath: '/recipe'
      preLoaderRoute: typeof NavbarAuthedRecipeSidebarImport
      parentRoute: typeof NavbarAuthedRecipeRoute
    }
    '/_navbar/_authed/recipe/new': {
      id: '/_navbar/_authed/recipe/new'
      path: '/new'
      fullPath: '/recipe/new'
      preLoaderRoute: typeof NavbarAuthedRecipeNewImport
      parentRoute: typeof NavbarAuthedRecipeImport
    }
    '/_navbar/_authed/recipe/_sidebar/$recipeId': {
      id: '/_navbar/_authed/recipe/_sidebar/$recipeId'
      path: '/$recipeId'
      fullPath: '/recipe/$recipeId'
      preLoaderRoute: typeof NavbarAuthedRecipeSidebarRecipeIdImport
      parentRoute: typeof NavbarAuthedRecipeSidebarImport
    }
    '/_navbar/_authed/recipe/_sidebar/': {
      id: '/_navbar/_authed/recipe/_sidebar/'
      path: '/'
      fullPath: '/recipe/'
      preLoaderRoute: typeof NavbarAuthedRecipeSidebarIndexImport
      parentRoute: typeof NavbarAuthedRecipeSidebarImport
    }
  }
}

// Create and export the route tree

interface NavbarAuthedRecipeSidebarRouteChildren {
  NavbarAuthedRecipeSidebarRecipeIdRoute: typeof NavbarAuthedRecipeSidebarRecipeIdRoute
  NavbarAuthedRecipeSidebarIndexRoute: typeof NavbarAuthedRecipeSidebarIndexRoute
}

const NavbarAuthedRecipeSidebarRouteChildren: NavbarAuthedRecipeSidebarRouteChildren =
  {
    NavbarAuthedRecipeSidebarRecipeIdRoute:
      NavbarAuthedRecipeSidebarRecipeIdRoute,
    NavbarAuthedRecipeSidebarIndexRoute: NavbarAuthedRecipeSidebarIndexRoute,
  }

const NavbarAuthedRecipeSidebarRouteWithChildren =
  NavbarAuthedRecipeSidebarRoute._addFileChildren(
    NavbarAuthedRecipeSidebarRouteChildren,
  )

interface NavbarAuthedRecipeRouteChildren {
  NavbarAuthedRecipeSidebarRoute: typeof NavbarAuthedRecipeSidebarRouteWithChildren
  NavbarAuthedRecipeNewRoute: typeof NavbarAuthedRecipeNewRoute
}

const NavbarAuthedRecipeRouteChildren: NavbarAuthedRecipeRouteChildren = {
  NavbarAuthedRecipeSidebarRoute: NavbarAuthedRecipeSidebarRouteWithChildren,
  NavbarAuthedRecipeNewRoute: NavbarAuthedRecipeNewRoute,
}

const NavbarAuthedRecipeRouteWithChildren =
  NavbarAuthedRecipeRoute._addFileChildren(NavbarAuthedRecipeRouteChildren)

interface NavbarAuthedRouteChildren {
  NavbarAuthedRecipeRoute: typeof NavbarAuthedRecipeRouteWithChildren
}

const NavbarAuthedRouteChildren: NavbarAuthedRouteChildren = {
  NavbarAuthedRecipeRoute: NavbarAuthedRecipeRouteWithChildren,
}

const NavbarAuthedRouteWithChildren = NavbarAuthedRoute._addFileChildren(
  NavbarAuthedRouteChildren,
)

interface NavbarRouteChildren {
  NavbarAuthedRoute: typeof NavbarAuthedRouteWithChildren
  NavbarIndexRoute: typeof NavbarIndexRoute
}

const NavbarRouteChildren: NavbarRouteChildren = {
  NavbarAuthedRoute: NavbarAuthedRouteWithChildren,
  NavbarIndexRoute: NavbarIndexRoute,
}

const NavbarRouteWithChildren =
  NavbarRoute._addFileChildren(NavbarRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof NavbarAuthedRouteWithChildren
  '/sandbox': typeof SandboxRoute
  '/login': typeof AuthLoginRoute
  '/password-forgot': typeof AuthPasswordForgotRoute
  '/password-reset': typeof AuthPasswordResetRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof NavbarIndexRoute
  '/recipe': typeof NavbarAuthedRecipeSidebarRouteWithChildren
  '/recipe/new': typeof NavbarAuthedRecipeNewRoute
  '/recipe/$recipeId': typeof NavbarAuthedRecipeSidebarRecipeIdRoute
  '/recipe/': typeof NavbarAuthedRecipeSidebarIndexRoute
}

export interface FileRoutesByTo {
  '/sandbox': typeof SandboxRoute
  '/login': typeof AuthLoginRoute
  '/password-forgot': typeof AuthPasswordForgotRoute
  '/password-reset': typeof AuthPasswordResetRoute
  '/signup': typeof AuthSignupRoute
  '': typeof NavbarAuthedRouteWithChildren
  '/': typeof NavbarIndexRoute
  '/recipe': typeof NavbarAuthedRecipeSidebarIndexRoute
  '/recipe/new': typeof NavbarAuthedRecipeNewRoute
  '/recipe/$recipeId': typeof NavbarAuthedRecipeSidebarRecipeIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_navbar': typeof NavbarRouteWithChildren
  '/sandbox': typeof SandboxRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/password-forgot': typeof AuthPasswordForgotRoute
  '/_auth/password-reset': typeof AuthPasswordResetRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_navbar/_authed': typeof NavbarAuthedRouteWithChildren
  '/_navbar/': typeof NavbarIndexRoute
  '/_navbar/_authed/recipe': typeof NavbarAuthedRecipeRouteWithChildren
  '/_navbar/_authed/recipe/_sidebar': typeof NavbarAuthedRecipeSidebarRouteWithChildren
  '/_navbar/_authed/recipe/new': typeof NavbarAuthedRecipeNewRoute
  '/_navbar/_authed/recipe/_sidebar/$recipeId': typeof NavbarAuthedRecipeSidebarRecipeIdRoute
  '/_navbar/_authed/recipe/_sidebar/': typeof NavbarAuthedRecipeSidebarIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/sandbox'
    | '/login'
    | '/password-forgot'
    | '/password-reset'
    | '/signup'
    | '/'
    | '/recipe'
    | '/recipe/new'
    | '/recipe/$recipeId'
    | '/recipe/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sandbox'
    | '/login'
    | '/password-forgot'
    | '/password-reset'
    | '/signup'
    | ''
    | '/'
    | '/recipe'
    | '/recipe/new'
    | '/recipe/$recipeId'
  id:
    | '__root__'
    | '/_navbar'
    | '/sandbox'
    | '/_auth/login'
    | '/_auth/password-forgot'
    | '/_auth/password-reset'
    | '/_auth/signup'
    | '/_navbar/_authed'
    | '/_navbar/'
    | '/_navbar/_authed/recipe'
    | '/_navbar/_authed/recipe/_sidebar'
    | '/_navbar/_authed/recipe/new'
    | '/_navbar/_authed/recipe/_sidebar/$recipeId'
    | '/_navbar/_authed/recipe/_sidebar/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  NavbarRoute: typeof NavbarRouteWithChildren
  SandboxRoute: typeof SandboxRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPasswordForgotRoute: typeof AuthPasswordForgotRoute
  AuthPasswordResetRoute: typeof AuthPasswordResetRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  NavbarRoute: NavbarRouteWithChildren,
  SandboxRoute: SandboxRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPasswordForgotRoute: AuthPasswordForgotRoute,
  AuthPasswordResetRoute: AuthPasswordResetRoute,
  AuthSignupRoute: AuthSignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_navbar",
        "/sandbox",
        "/_auth/login",
        "/_auth/password-forgot",
        "/_auth/password-reset",
        "/_auth/signup"
      ]
    },
    "/_navbar": {
      "filePath": "_navbar.tsx",
      "children": [
        "/_navbar/_authed",
        "/_navbar/"
      ]
    },
    "/sandbox": {
      "filePath": "sandbox.tsx"
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx"
    },
    "/_auth/password-forgot": {
      "filePath": "_auth/password-forgot.tsx"
    },
    "/_auth/password-reset": {
      "filePath": "_auth/password-reset.tsx"
    },
    "/_auth/signup": {
      "filePath": "_auth/signup.tsx"
    },
    "/_navbar/_authed": {
      "filePath": "_navbar/_authed.tsx",
      "parent": "/_navbar",
      "children": [
        "/_navbar/_authed/recipe"
      ]
    },
    "/_navbar/": {
      "filePath": "_navbar/index.tsx",
      "parent": "/_navbar"
    },
    "/_navbar/_authed/recipe": {
      "filePath": "_navbar/_authed/recipe",
      "parent": "/_navbar/_authed",
      "children": [
        "/_navbar/_authed/recipe/_sidebar",
        "/_navbar/_authed/recipe/new"
      ]
    },
    "/_navbar/_authed/recipe/_sidebar": {
      "filePath": "_navbar/_authed/recipe/_sidebar.tsx",
      "parent": "/_navbar/_authed/recipe",
      "children": [
        "/_navbar/_authed/recipe/_sidebar/$recipeId",
        "/_navbar/_authed/recipe/_sidebar/"
      ]
    },
    "/_navbar/_authed/recipe/new": {
      "filePath": "_navbar/_authed/recipe/new.tsx",
      "parent": "/_navbar/_authed/recipe"
    },
    "/_navbar/_authed/recipe/_sidebar/$recipeId": {
      "filePath": "_navbar/_authed/recipe/_sidebar/$recipeId.tsx",
      "parent": "/_navbar/_authed/recipe/_sidebar"
    },
    "/_navbar/_authed/recipe/_sidebar/": {
      "filePath": "_navbar/_authed/recipe/_sidebar/index.tsx",
      "parent": "/_navbar/_authed/recipe/_sidebar"
    }
  }
}
ROUTE_MANIFEST_END */
