version: '3.8'

x-load-secrets-config: &load-secrets-config
  configs:
    - source: load-secrets.sh
      target: /usr/local/bin/load-secrets.sh
      mode: 0555

services:
  postgres:
    image: 192.168.1.30:5000/tanstack-start-template/database:1.0.0
    secrets:
      - tanstack-start-template_DB_PASSWORD
    <<: *load-secrets-config
    environment:
      PROJECT_NAME: tanstack-start-template
      POSTGRES_DB: tanstack-start-template
      POSTGRES_USER: app
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  drizzle:
    image: 192.168.1.30:5000/tanstack-start-template/drizzle:1.0.0
    secrets:
      - tanstack-start-template_DB_PASSWORD
    <<: *load-secrets-config
    environment:
      PROJECT_NAME: tanstack-start-template
      DB_USER: app
      DB_NAME: tanstack-start-template
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
    networks:
      - app-network
    # One-off task to run DB migrations.
    deploy:
      replicas: 1
      restart_policy:
        condition: none

  app:
    image: 192.168.1.30:5000/tanstack-start-template/app:1.3.0
    secrets:
      - tanstack-start-template_DB_PASSWORD
      - tanstack-start-template_BETTER_AUTH_SECRET
      - tanstack-start-template_SMTP_PASSWORD
    <<: *load-secrets-config
    environment:
      PROJECT_NAME: tanstack-start-template
      DB_USER: app
      DB_NAME: tanstack-start-template
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - '3000:3000'
    depends_on:
      - migrations
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:

secrets:
  tanstack-start-template_DB_PASSWORD:
    external: true
  tanstack-start-template_BETTER_AUTH_SECRET:
    external: true
  tanstack-start-template_SMTP_PASSWORD:
    external: true

configs:
  load-secrets.sh:
    external: true
