version: '3.8'
services:
  postgres:
    image: postgres:16.4-alpine
    secrets:
      - DB_PASSWORD
    configs:
      - source: load-secrets.sh
        target: /usr/local/bin/load-secrets.sh
        mode: 0555
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    entrypoint: >
      bash -c "
        source /usr/local/bin/load-secrets.sh DB_PASSWORD;
        export POSTGRES_PASSWORD=$$DB_PASSWORD;
        exec $$@
      "

  drizzle:
    image: ${DOCKER_REGISTRY}/tanstack-start-template/drizzle:latest
    secrets:
      - DB_PASSWORD
    configs:
      - source: load-secrets.sh
        target: /usr/local/bin/load-secrets.sh
        mode: 0555
    environment:
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
    networks:
      - app-network
    # One-off task to run DB migrations.
    deploy:
      replicas: 1
      restart_policy:
        condition: none

  app:
    image: ${DOCKER_REGISTRY}/tanstack-start-template/app:latest
    secrets:
      - DB_PASSWORD
    configs:
      - source: load-secrets.sh
        target: /usr/local/bin/load-secrets.sh
        mode: 0555
    environment:
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - '3000:3000'
    depends_on:
      - migrations
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:

secrets:
  DB_PASSWORD:
    external: true

configs:
  load-secrets.sh:
    external: true
