version: '3.8'

x-load-secrets-config: &load-secrets-config
  configs:
    - source: load-secrets.sh
      target: /usr/local/bin/load-secrets.sh
      mode: 0555

services:
  postgres:
    image: ${DOCKER_REGISTRY}/${PROJECT_NAME}/database:${database_VERSION}
    secrets:
      - ${PROJECT_NAME}_DB_PASSWORD
    <<: *load-secrets-config
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  drizzle:
    image: ${DOCKER_REGISTRY}/${PROJECT_NAME}/drizzle:${drizzle_VERSION}
    secrets:
      - ${PROJECT_NAME}_DB_PASSWORD
    <<: *load-secrets-config
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
    networks:
      - app-network
    # One-off task to run DB migrations.
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
        window: 120s

  app:
    image: ${DOCKER_REGISTRY}/${PROJECT_NAME}/app:${app_VERSION}
    secrets:
      - ${PROJECT_NAME}_DB_PASSWORD
      - ${PROJECT_NAME}_BETTER_AUTH_SECRET
      - ${PROJECT_NAME}_SMTP_PASSWORD
    <<: *load-secrets-config
    environment:
      PUBLIC_BASEURL: ${PUBLIC_BASEURL}
      PROJECT_NAME: ${PROJECT_NAME}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - '3000:3000'
    depends_on:
      - migrations
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:

secrets:
  ${PROJECT_NAME}_DB_PASSWORD:
    external: true
  ${PROJECT_NAME}_BETTER_AUTH_SECRET:
    external: true
  ${PROJECT_NAME}_SMTP_PASSWORD:
    external: true

configs:
  load-secrets.sh:
    external: true
