version: '3.8'

x-load-secrets-config: &load-secrets-config
  configs:
    - source: load-secrets.sh
      target: /usr/local/bin/load-secrets.sh
      mode: 0555

services:
  database:
    image: 192.168.1.30:5000/tanstack-start-template/database:1.0.0
    secrets:
      - tanstack-start-template_DB_PASSWORD
    <<: *load-secrets-config
    environment:
      PROJECT_NAME: tanstack-start-template
      POSTGRES_DB: tanstack-start-template
      POSTGRES_USER: app
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      labels:
        - 'traefik.enable=false'

  migrations:
    image: 192.168.1.30:5000/tanstack-start-template/drizzle:1.1.0
    secrets:
      - tanstack-start-template_DB_PASSWORD
    <<: *load-secrets-config
    environment:
      PROJECT_NAME: tanstack-start-template
      DB_USER: app
      DB_NAME: tanstack-start-template
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
        window: 120s
      labels:
        - 'traefik.enable=false'

  app:
    image: 192.168.1.30:5000/tanstack-start-template/app:1.4.0
    secrets:
      - tanstack-start-template_DB_PASSWORD
      - tanstack-start-template_BETTER_AUTH_SECRET
      - tanstack-start-template_SMTP_PASSWORD
    <<: *load-secrets-config
    environment:
      PUBLIC_BASEURL: https://donut.yaoshiko.com
      PROJECT_NAME: tanstack-start-template
      DB_USER: app
      DB_NAME: tanstack-start-template
      DB_HOST: database
      DB_PORT: 5432
    depends_on:
      - migrations
    networks:
      - app-network
      - reverse-proxy-network
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.app.rule=Host(`donut.yaoshiko.com`)'
        - 'traefik.http.routers.app.entrypoints=websecure'
        - 'traefik.http.routers.app.tls.certresolver=myresolver'
        - 'traefik.http.services.app.loadbalancer.server.port=3000'
      mode: global
      restart_policy:
        condition: on-failure

  reverse-proxy:
    image: traefik:v3.3.6
    command:
      - '--providers.swarm.endpoint=unix:///var/run/docker.sock'
      - '--providers.swarm.exposedbydefault=false'
      - '--providers.swarm.network=reverse-proxy-network'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.internal.address=:8080'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
      - '--certificatesresolvers.myresolver.acme.dnschallenge=true'
      - '--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare'
      - '--certificatesresolvers.myresolver.acme.email=nicola.barletta@outlook.it'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
      # TODO: Protect dashboard with auth.
      - '--api.dashboard=true'
      # FIXME: Temporary. Remove this.
      - '--certificatesresolvers.myresolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory'
    secrets:
      - tanstack-start-template_CF_DNS_API_TOKEN
    environment:
      - CF_DNS_API_TOKEN_FILE=/run/secrets/tanstack-start-template_CF_DNS_API_TOKEN
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/letsencrypt
    networks:
      - reverse-proxy-network
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.traefik.rule=PathPrefix(`/`)'
        - 'traefik.http.routers.traefik.service=api@internal'
        - 'traefik.http.routers.traefik.entrypoints=internal'
        - 'traefik.http.services.traefik.loadbalancer.server.port=8080'
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:
  traefik-certificates:

networks:
  app-network:
  reverse-proxy-network:

secrets:
  tanstack-start-template_DB_PASSWORD:
    external: true
  tanstack-start-template_BETTER_AUTH_SECRET:
    external: true
  tanstack-start-template_SMTP_PASSWORD:
    external: true
  tanstack-start-template_CF_DNS_API_TOKEN:
    external: true

configs:
  load-secrets.sh:
    external: true
