version: '3.8'

x-load-secrets-config: &load-secrets-config
  configs:
    - source: load-secrets.sh
      target: /usr/local/bin/load-secrets.sh
      mode: 0555

services:
  traefik:
    image: traefik:v3.3.6
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.service=api@internal'
      - 'traefik.http.routers.traefik.entrypoints=websecure'
      - 'traefik.http.routers.traefik.tls.certresolver=myresolver'
    command:
      - '--providers.docker.swarmMode=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
      - '--api.dashboard=true'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/letsencrypt
    networks:
      - traefik
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    environment:
      ACME_EMAIL: ${ACME_EMAIL}

  postgres:
    image: ${DOCKER_REGISTRY}/${PROJECT_NAME}/database:${database_VERSION}
    secrets:
      - ${PROJECT_NAME}_DB_PASSWORD
    <<: *load-secrets-config
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  drizzle:
    image: ${DOCKER_REGISTRY}/${PROJECT_NAME}/drizzle:${drizzle_VERSION}
    secrets:
      - ${PROJECT_NAME}_DB_PASSWORD
    <<: *load-secrets-config
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
    networks:
      - app-network
      - traefik
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
        window: 120s

  app:
    image: ${DOCKER_REGISTRY}/${PROJECT_NAME}/app:${app_VERSION}
    secrets:
      - ${PROJECT_NAME}_DB_PASSWORD
      - ${PROJECT_NAME}_BETTER_AUTH_SECRET
      - ${PROJECT_NAME}_SMTP_PASSWORD
    <<: *load-secrets-config
    environment:
      PUBLIC_BASEURL: ${PUBLIC_BASEURL}
      PROJECT_NAME: ${PROJECT_NAME}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.app.rule=Host(`${PUBLIC_BASEURL}`)'
      - 'traefik.http.routers.app.entrypoints=websecure'
      - 'traefik.http.routers.app.tls.certresolver=myresolver'
    depends_on:
      - drizzle
    networks:
      - app-network

volumes:
  postgres_data:
  traefik-certificates:

networks:
  app-network:
  traefik:

secrets:
  ${PROJECT_NAME}_DB_PASSWORD:
    external: true
  ${PROJECT_NAME}_BETTER_AUTH_SECRET:
    external: true
  ${PROJECT_NAME}_SMTP_PASSWORD:
    external: true

configs:
  load-secrets.sh:
    external: true
