version: '3.8'

x-load-secrets-config: &load-secrets-config
  configs:
    - source: load-secrets.sh
      target: /usr/local/bin/load-secrets.sh
      mode: 0555

services:
  database:
    image: ${DOCKER_REGISTRY}/${PROJECT_NAME}/database:${database_VERSION}
    secrets:
      - ${PROJECT_NAME}_DB_PASSWORD
    <<: *load-secrets-config
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      labels:
        - 'traefik.enable=false'

  migrations:
    image: ${DOCKER_REGISTRY}/${PROJECT_NAME}/drizzle:${drizzle_VERSION}
    secrets:
      - ${PROJECT_NAME}_DB_PASSWORD
    <<: *load-secrets-config
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
        window: 120s
      labels:
        - 'traefik.enable=false'

  app:
    image: ${DOCKER_REGISTRY}/${PROJECT_NAME}/app:${app_VERSION}
    secrets:
      - ${PROJECT_NAME}_DB_PASSWORD
      - ${PROJECT_NAME}_BETTER_AUTH_SECRET
      - ${PROJECT_NAME}_SMTP_PASSWORD
    <<: *load-secrets-config
    environment:
      PUBLIC_BASEURL: ${PUBLIC_BASEURL}
      PROJECT_NAME: ${PROJECT_NAME}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: database
      DB_PORT: 5432
    depends_on:
      - migrations
    networks:
      - app-network
      - portainer_reverse-proxy-network
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.app.rule=PathPrefix(`/`)'
        - 'traefik.http.routers.app.entrypoints=websecure'
        - 'traefik.http.routers.app.tls.certresolver=myresolver'
        - 'traefik.http.services.app.loadbalancer.server.port=3000'
      mode: global
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:

networks:
  app-network:
  portainer_reverse-proxy-network:
    external: true

secrets:
  ${PROJECT_NAME}_DB_PASSWORD:
    external: true
  ${PROJECT_NAME}_BETTER_AUTH_SECRET:
    external: true
  ${PROJECT_NAME}_SMTP_PASSWORD:
    external: true

configs:
  load-secrets.sh:
    external: true
