type: automation
language: bash
tags:
  - swarm

dependsOn:
  - 'tanstack-start-template'
  - 'drizzle'
  - 'database'

tasks:
  deploy-local:
    description: Deploy the app to local Docker Swarm.
    deps:
      - '^:docker-push'
      - '~:deploy'
    local: true
    command: docker stack deploy -c docker-swarm.yml $PROJECT_NAME

  rm-stack-local:
    description: Remove the app from local Docker Swarm.
    local: true
    command: docker stack rm $PROJECT_NAME

  deploy:
    description: Update Docker Swarm template.
    inputs:
      - '/.versions'
      - '/scripts/prepare-docker-swarm.sh'
      - './docker-swarm-template.yml'
    outputs:
      - './docker-swarm.yml'
    deps:
      - '^:docker-push'
    command: bash $workspaceRoot/scripts/prepare-docker-swarm.sh $workspaceRoot/.versions
