type: automation
language: bash
tags:
  - swarm

dependsOn:
  - 'tanstack-start-template'
  - 'drizzle'
  - 'database'

tasks:
  deploy-local:
    description: Deploy the app to local Docker Swarm.
    deps:
      - '~:setup-docker-swarm'
    local: true
    command: docker stack deploy -c docker-swarm.yml $PROJECT_NAME

  rm-stack-local:
    description: Remove the app from local Docker Swarm.
    local: true
    command: docker stack rm $PROJECT_NAME

  setup-docker-swarm:
    description: Update Docker Swarm template.
    options:
      cache: false
    inputs:
      - '/scripts/prepare-docker-swarm.sh'
      - './docker-swarm-template.yml'
    outputs:
      - './docker-swarm.yml'
    command: bash $workspaceRoot/scripts/prepare-docker-swarm.sh

  deploy:
    description: Trigger a Portainer redeploy on deploy branch.
    options:
      cache: false
    inputs:
      - '/scripts/deploy.sh'
    command: bash $workspaceRoot/scripts/deploy.sh
