type: automation
language: bash
tags:
  - swarm

dependsOn:
  - 'tanstack-start-template'
  - 'drizzle'
  - 'database'

tasks:
  docker-stack:
    description: Deploy the app to local Docker Swarm.
    deps:
      - '^:docker-push'
      - '~:prepare-swarm-template'
    local: true
    command: docker stack deploy -c docker-swarm.yml $PROJECT_NAME

  docker-stack-rm:
    description: Remove the app from local Docker Swarm.
    local: true
    command: docker stack rm $PROJECT_NAME

  prepare-swarm-template:
    description: Update Docker Swarm template.
    inputs:
      - './docker-swarm-template.yml'
    outputs:
      - './docker-swarm.yml'
    deps:
      - '^:docker-push'
    options:
      envFile:
        - '.env'
        - '/.env'
        - '/.versions'
    command: |
      envsubst < docker-swarm-template.yml > docker-swarm.yml

  deploy:
    description: Deploy dockers and update Docker Swarm template.
    deps:
      - '^:docker-push'
      - '~:prepare-swarm-template'
