tasks:
  # TODO: Manage image versioning and retention.
  docker-build:
    description: Build a Docker image with semantic versioning.
    inputs:
      - '/scripts/docker-build.sh'
      - './Dockerfile'
    command: bash $workspaceRoot/scripts/docker-build.sh $workspaceRoot/.versions

  docker-push:
    description: Push Docker images to the registry.
    deps:
      - '~:docker-build'
    command: bash $workspaceRoot/scripts/docker-push.sh $workspaceRoot/.versions
