tasks:
  push-image:
    description: Build a Docker image with semantic versioning and push to the registry.
    inputs:
      - '/scripts/push-image.sh'
      - './Dockerfile'
    command: bash $workspaceRoot/scripts/push-image.sh
