fileGroups:
  sources:
    - 'src/**/*'
    - 'app/**/*'
    - 'public/**/*'
    - '.env'

tasks:
  dev:
    description: Start the development server.
    command: pnpm dev
    local: true
    inputs:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '@globs(sources)'
