name: Build images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed to merge branches

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Verify Docker
        run: |
          docker --version
          docker-compose --version || echo "Docker Compose not available"

      - name: Cache Moon workspace
        uses: actions/cache@v3
        with:
          path: |
            .moon/cache
            .moon/toolchain
          key: moon-${{ runner.os }}-${{ hashFiles('.moon/workspace.yml') }}
          restore-keys: |
            moon-${{ runner.os }}-

      - name: Run affected tests
        run: pnpm moon :test --affected

      - name: Build and push Docker images
        run: pnpm moon :setup-docker-swarm

      - name: Configure Git
        run: |
          git config user.name "GitHub CI Bot"
          git config user.email "ci@yaoshiko.com"

      - name: Trigger deploy
        run: |
          # Stash any remaining local changes to avoid conflicts
          git stash push -m "Temporary stash before deploy"

          # Make sure we have the latest master (including our version commit)
          git fetch origin
          git checkout master
          git pull origin master

          # Check out the deploy branch
          git checkout deploy || git checkout -b deploy

          # Merge master into deploy with all changes
          git merge origin/master --no-ff -m "[CI] Deploy: Merge master with updated versions"

          # Apply any stashed changes back
          git stash pop || echo "No stash to apply"

          # Add any additional changes and commit if needed
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "[CI] Add build artifacts to deploy"
          fi

          # Push the deploy branch
          git push origin deploy
