name: Build images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    outputs:
      should_deploy: ${{ steps.trigger_deploy.outputs.should_deploy }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Moon toolchain
        uses: 'moonrepo/setup-toolchain@v0'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Verify Docker
        run: |
          docker --version
          docker-compose --version || echo "Docker Compose not available"

      - name: Configure Git
        run: |
          git config user.name "GitHub CI Bot"
          git config user.email "ci@yaoshiko.com"

      - name: Run affected tests
        run: moon ci :test :lint

      - name: Build and push images
        run: moon ci :build :push-image

      - name: Setup Docker Swarm
        run: moon :setup-docker-swarm

      - name: Trigger deploy
        id: trigger_deploy
        run: |
          DOCKER_SWARM_PATH=tools/deploy/docker-swarm.yml

          if [ ! -f ${DOCKER_SWARM_PATH} ]; then
            echo "No deploy configuration file found, skipping deploy"
            echo "should_deploy=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "Deploy configuration file found, preparing deploy branch"

          # Prepare deploy branch
          git fetch origin deploy || true

          # Manually override docker swarm file to avoid conflicts
          mv ${DOCKER_SWARM_PATH} ${DOCKER_SWARM_PATH}_TMP
          git checkout deploy
          mv ${DOCKER_SWARM_PATH}_TMP ${DOCKER_SWARM_PATH}

          # Check if the file actually changed compared to what's in the deploy branch
          if git diff --quiet HEAD -- ${DOCKER_SWARM_PATH}; then
            echo "No changes in deploy configuration, skipping deploy"
            echo "should_deploy=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "Changes detected in deploy configuration, proceeding with deploy"
          echo "should_deploy=true" >> $GITHUB_OUTPUT

          # Proceed with merge and deploy
          git merge --no-commit --no-ff $GITHUB_SHA || {
            echo "Conflict detected, resolving in favor of master branch"
            git checkout --theirs .
            git add .
          }

          git commit -m "[CI] Deploy"
          git push origin deploy --force-with-lease
