name: Build images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Moon toolchain
        uses: 'moonrepo/setup-toolchain@v0'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Verify Docker
        run: |
          docker --version
          docker-compose --version || echo "Docker Compose not available"

      # Check what's actually affected before running tests
      - name: Check affected projects
        id: affected-check
        run: |
          # Get affected projects and handle Moon's JSON format properly
          AFFECTED_OUTPUT=$(moon query projects --affected --json)

          # Extract just the project IDs from Moon's JSON response
          AFFECTED_COUNT=$(echo "$AFFECTED_OUTPUT" | jq '.projects | length')
          AFFECTED_IDS=$(echo "$AFFECTED_OUTPUT" | jq -r '.projects[].id' | tr '\n' ',' | sed 's/,$//')

          echo "affected-count=$AFFECTED_COUNT" >> $GITHUB_OUTPUT
          echo "affected-ids=$AFFECTED_IDS" >> $GITHUB_OUTPUT

          # Check if any projects are actually affected
          if [ "$AFFECTED_COUNT" -eq 0 ]; then
            echo "has-affected=false" >> $GITHUB_OUTPUT
            echo "No projects affected, skipping builds"
          else
            echo "has-affected=true" >> $GITHUB_OUTPUT
            echo "Found $AFFECTED_COUNT affected projects: $AFFECTED_IDS"
          fi

      - name: Run affected tests
        if: steps.affected-check.outputs.has-affected == 'true'
        run: moon ci :test :lint

      - name: Build Docker images
        if: steps.affected-check.outputs.has-affected == 'true'
        run: moon ci :build

      - name: Push Docker images
        if: steps.affected-check.outputs.has-affected == 'true'
        run: moon ci :push-image

      - name: Setup Docker Swarm
        if: steps.affected-check.outputs.has-affected == 'true'
        run: moon ci :setup-docker-swarm

      - name: Configure Git
        if: steps.affected-check.outputs.has-affected == 'true'
        run: |
          git config user.name "GitHub CI Bot"
          git config user.email "ci@yaoshiko.com"

      - name: Trigger deploy
        if: steps.affected-check.outputs.has-affected == 'true'
        run: |
          git fetch origin deploy || true
          git checkout -B deploy origin/deploy || git checkout -b deploy

          git merge --no-commit --no-ff $GITHUB_SHA || {
            echo "Conflict detected, resolving in favor of master branch"
            git checkout --theirs .
            git add .
          }

          if ! git diff --quiet tools/deploy/docker-swarm.yml; then
            echo "Changes detected in deploy configuration, proceeding with deploy"

            git add tools/deploy/docker-swarm.yml
            git commit -m "[CI] Deploy"
            git push origin deploy --force-with-lease

          else
            echo "No changes in deploy configuration, skipping deploy"
            git merge --abort || true
          fi
