name: Build images & trigger deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed to merge branches

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install deps
        run: pnpm install

      - name: Verify Docker
        run: |
          docker --version
          docker-compose --version || echo "Docker Compose not available"

      - name: Cache Moon workspace
        uses: actions/cache@v3
        with:
          path: |
            .moon/cache
            .moon/toolchain
          key: moon-${{ runner.os }}-${{ hashFiles('.moon/workspace.yml') }}
          restore-keys: |
            moon-${{ runner.os }}-

      - name: Run affected tests
        run: pnpm moon run :test --affected

      - name: Build and push Docker images
        run: pnpm moon :setup-docker-swarm

      - name: Configure Git
        run: |
          git config user.name "GitHub CI Bot"
          git config user.email "ci@yaoshiko.com"

      - name: Trigger deploy
        run: |
          # Fetch all branches
          git fetch origin

          # Check out the deploy branch
          git checkout deploy || git checkout -b deploy

          # Merge master into deploy (without committing yet)
          git merge origin/master --no-ff --no-commit -m "[CI] Deploy: Merge master with updated versions"

          # Add any changes made during the build process (like .versions)
          git add .

          # Complete the merge commit
          git commit -m "[CI] Deploy: Merge master with updated versions and build artifacts"

          # Push the deploy branch
          git push origin deploy
