name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    outputs:
      should_deploy: ${{ steps.trigger_deploy.outputs.should_deploy }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Moon toolchain
        uses: 'moonrepo/setup-toolchain@v0'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Verify Docker
        run: |
          docker --version
          docker-compose --version || echo "Docker Compose not available"

      - name: Configure Git
        run: |
          git config user.name "GitHub CI Bot"
          git config user.email "ci@yaoshiko.com"

      - name: Run affected tests
        run: moon ci :test :lint

      - name: Build and push images
        run: moon ci :build :push-image

      - name: Merge into deploy branch
        run: |
          # Checkout deploy branch
          git checkout deploy
          git pull -r

          # Merge changes from master into deploy
          git merge --no-edit --no-ff -m "[CI] Deploy" master

      - name: Update Docker Swarm compose file
        run: moon :setup-docker-swarm

      - name: Trigger deploy
        id: trigger_deploy
        run: |
          DOCKER_SWARM_PATH=tools/deploy/docker-swarm.yml

          git add ${DOCKER_SWARM_PATH} || {
            echo "No changes to deploy configuration file, skipping deploy"
            exit 0
          }

          echo "Deploy configuration file found, preparing deploy branch"

          git commit -a --amend --no-edit
          git push -u origin deploy || {
            echo "Failed to push changes to deploy branch, skipping deploy"
            exit 0
          }
