name: Trigger Portainer Deployment

on:
  push:
    branches:
      - deploy

jobs:
  trigger-portainer:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Trigger Portainer Stack Redeploy
        id: redeploy
        run: moon :deploy
